<<<<<<< HEAD
name: Actualizar datos de la app
=======
name: Actualizar datos
>>>>>>> 47927a3de2a3aa752656524c7a411b1122843623

on:
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run update script
      run: |
<<<<<<< HEAD
        python actualizar_clasificacion.py
=======
        python actualizar_clasificacion.py
>>>>>>> 47927a3de2a3aa752656524c7a411b1122843623
